### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by medrockstar** [STS-Rosario/carpoolear#44]
Hi,

these are are occurs when the users are login :

GET http://backend/api/trips?is_passenger=false&page=1&page_size=20 500 (Internal Server Error)
GET http://backend/api/users/requests 500 (Internal Server Error)
GET http://backend/api/users/my-trips?as_driver=false 500 (Internal Server Error)

And nothing is showing.

**Comment by p4bl1t0** [comment]
This is a backend error, is not a frontend issue. Please check your apache log for more information an post an issue in carpoolear_backend.
