### ISSUE TITLE
Login issue with Facebook

### ISSUE THREAD

**Issue by martin0995** [STS-Rosario/carpoolear#97]
There is an error while logging in with Facebook:
<img width="844" alt="Carpoolear login issue with Facebook" src="https://github.com/STS-Rosario/carpoolear/assets/63241224/920caf16-b5d9-497b-a506-6ba70c3dd074">

**Comment by p4bl1t0** [comment]
We're in the way of moving off facebook. It you need to convert your account to user/password account please contact support. Regards
